<div class="text-center pt-3 pb-2">
    <h2 class="my-4">Faites votre message</h2>
</div>

<!-- CODE HTML DU MESSAGE -->

<form action="/message" method="POST">
    <fieldset>
        
        <div class="mb-3 form-group">
            <label for="firstname">Prénom</label>
            <input type="text" name="firstname" class="form-control" id="firstname" placeholder="Votre prénom">    
            <?php if(isset($errors['firstname'])): ?>
                <p class="mt-3 alert alert-danger"><?=htmlspecialchars($errors['firstname']);?></p>
            <?php endif; ?>
        </div>

        <div class="mb-3 form-group">
            <label for="email">Email</label>
            <input type="text" name="email" class="form-control" id="email" placeholder="Votre email">    
            <?php if(isset($errors['email'])): ?>
                <p class="mt-3 alert alert-danger"><?=htmlspecialchars($errors['email']);?></p>
            <?php endif; ?>
        </div>

        <div class="mb-3 form-group">
            <label for="subject">Sujet</label>
            <select name="subject" class="form-control" id="subject">
                <?php foreach ($subjects as $s): ?>
                    <?php $selected = $subject == $s['id'] ? 'selected' : ''; ?>
                    <option <?=$selected;?> value="<?=intval($s['id'])?>"><?=htmlspecialchars($s['subject_label'])?></option>
                <?php endforeach; ?>
            </select>
            <?php if (isset($errors['subject'])): ?>
                <p class="mt-3 alert alert-danger"><?=htmlspecialchars($errors['subject']);?></p>
            <?php endif; ?>
        </div>

        <div class="mb-3 form-group">
            <label for="description">Message</label>
            <textarea type="text" name="description" class="form-control" id="description" placeholder="Votre message"></textarea>   
            <?php if(isset($errors['description'])): ?>
                <p class="mt-3 alert alert-danger"><?=htmlspecialchars($errors['description']);?></p>
            <?php endif; ?>
        </div>

        <div class="form-group">
            <input class="btn btn-secondary mt-4" type="submit" value="Envoyer votre message">
        </div>

    </fieldset>
</form>