<div id="container-moi" class="mt-10px d-flex">
    <img id="moi" src="img/moi.jpg" alt="Photo de moi-même">
    <p id="p-moi" class="mt-10px">Je m'appelle Paul Cudot, j'ai 21 ans. Je suis formé au métier de développeur web, Front-End (partie visible HTML5/CSS3/JavaScript) et Back-End (partie côté serveur PHP/SQL).
    <br>
    <strong><i class="fa-solid fa-compass"></i> <a target="_blank" href="img/monCv.pdf">Mon CV</a></strong>
    <br>
    <strong><i class="fa-brands fa-github"></i><a target="_blank" href="https://github.com/PaulCdt"> Mon compte GitHub</a></strong>
    <br>
    <strong><i class="fa-brands fa-linkedin"></i><a target="_blank" href="https://www.linkedin.com/in/paul-cudot-6717bb217/"> Mon profil LinkedIn</a></strong>
    </p>
</div>


<h5 class="mt-10px d-flex justify-content-center">Mes formations suivies</h5>

<div id="webforce3" class="mt-20px">
    <p class="mt-10px"><strong>WebForce3</strong></p>
    <p>Octobre 2022 - Février 2023</p>
    <div class="text-notcenter">
    <p> - Lors de cette formation en bootcamp (intensive) de 4 mois, j'ai appronfondis mes connaissances en HTML5 et CSS3, j'ai appris les languages JavaScprit, SQL et PHP tout en assimilant les bases du fonctionnement des frameworks Angular (JavaScript) et Symfony (PHP).</p>
    <p> - J'ai appris les méthodes de travail agiles, l'importance de certaines pratiques du numérique responsable et une première approche du CMS WordPress.
    </p>
    </div>
</div>

<div id="openclassrooms" class="mt-20px">
    <p class="mt-10px"><strong>OpenClassRooms</strong></p>
    <p>Juillet 2021 - Novembre 2021</p>
    <div class="text-notcenter">
    <p> - J'ai suivi pendant 4 mois la Prep'Apprentissage chez OpenClassRooms, j'ai appris les bases du métier de développeur ainsi que les languages HTML5 et CSS3. J'ai réalisé le projet Réservia sur 2 mois pendant la formation, qui était la page d'accueil d'un site factice de réservation de logements/voyages.</p>
    </div>
</div>



<h5 class="mt-20px d-flex justify-content-center">Cliquez sur les différents languages pour plus de détails !</h5>


<div class="d-flex justify-content-center">

    <!-- Container HTML5 -->

    <div id="html5" class="d-flex width-custom container-border-custom flex-direction-column justify-content-center align-items-center">
        <img class="html5" src="img/html5.png" alt="HTML5">
        <p>HTML5</p>
    </div>


    <!-- Container CSS3 -->

    <div id="css3" class="d-flex width-custom container-border-custom flex-direction-column justify-content-center align-items-center">
        <img class="css3" src="img/css3.png" alt="CSS3">
        <p class="mt-5px" >CSS3</p>
    </div>

    <!-- Container JS -->

    <div id="js" class="d-flex width-custom container-border-custom flex-direction-column justify-content-center align-items-center">
        <img class="js" src="img/js.png" alt="JavaScript">
        <p class="mt-5px" >JavaScript</p>
    </div>

    <!-- Contaire PHP -->

    <div id="php" class="d-flex width-custom container-border-custom flex-direction-column justify-content-center align-items-center">
        <img class="php" src="img/php.png" alt="PHP">
        <p class="mt-10px" >PHP</p>
    </div>

    <!-- Container SQL -->

    <div id="sql" class="d-flex width-custom container-border-custom flex-direction-column justify-content-center align-items-center">
        <img class="sql" src="img/sql.png" alt="SQL">
        <p class="mt-5px">SQL</p>
    </div>

</div>

    <!-- Les détails de mes compétences -->

    <div id="html-details">
        <p>Je maîtrise HTML5. Je connais l'importance des balises sémantiques dans le code et de la meta description pour le SEO (référencement du site).</p>
    </div>


    <div id="css-details">
        <p>Je suis à l'aise avec CSS3. Je sais utiliser les techniques pour placer les éléments comme FlexBox ou CSS Grid, ou encore styliser des éléments comme les boutons et les liens.</p>
    </div>

    
    <div id="js-details">
        <p>Je suis capable d'utiliser JavaScript pour rendre un site interactif, comme par exemple sur cette page, en faisant apparaître les paragraphes en cliquant sur les languages, et les faire dispraître en cliquant à nouveau sur le language en question.</p>
        <p>Je maîtrise également la POO JavaScript, ainsi que l'envoi de requête AJAX (Asynchronous JavaScript + XML), c'est-à-dire envoyer et recevoir des donnéees comme l'on pourrait faire en PHP mais sans avoir à recharger la page du site.</p>
    </div>

    <div id="php-details">
        <p>Je sais utiliser PHP pour envoyer des informations à une base de données et utiliser les informations rentrées pour rendre un site interactif. Par exemple, en vous faisant créer un compte sur ce site, puis vous connecter pour vous dire "Bonjour *votre prénom*" ainsi qu'avoir accès à certaines sections (ici, "Portfolio" et "Envoyer un message") ou fonctionnalités ("Déconnexion").</p>
        <p>Je maîtrise la POO (Programmation Orientée Object) en PHP, ainsi que la structure MVC (Model View Controller) qui, entre autres, me permet d'avoir des URL personnalisés.</p>
    </div>

    <div id="sql-details">
        <p>Je sais créer une base de données, la modifier, avoir des tables où stocker les données et lier certains éléments de différentes tables ensemble. Je maîtrise phpMyAdmin (application pour gérer ses bases de données plus facilement).</p>
    </div>


    <!-- Les frameworks utilisés -->

<h5 class="mt-20px d-flex justify-content-center">Cliquez sur les différents frameworks pour plus de détails !<span id="frameworkLink">Définition d'un framework</span></h5>

<div class="d-flex justify-content-center">

    <div id="angular" class="d-flex width-custom container-border-custom flex-direction-column justify-content-center align-items-center">
        <img class="angular" src="img/angular.png" alt="Angular">
        <p>Angular</p>
    </div>

    <div id="symfony" class="d-flex width-custom container-border-custom flex-direction-column justify-content-center align-items-center">
        <img class="symfony" src="img/symfony.png" alt="Symfony">
        <p class="mt-5px" >Symfony</p>
    </div>

</div>

    <div id="framework-def">
        <p>Un framework est un "cadre de travail", c'est-à-dire quelque chose que l'on installe sur notre ordinateur et qui va nous créer les bases d'une application web et nous aider. Plus précisement, il s'agit de fichiers remplis de code des personnes ayant mis en place le framework, et ce code donnera des instructions, contiendra des fonctionnalitées que l'on pourra appeller manuellement si besoin et bien plus encore.</p>
    </div>


    <div id="angular-details">
        <p>Je connais les bases d'Angular, je sais faire des animations simples avec, actuellement en cours d'acquisition.</p>
    </div>


    <div id="symfony-details">
        <p>Symfony est le framework sur lequel je suis le plus à l'aise, je sais créer des applications web basiques, également en cours d'acquisition.</p>
    </div>

    
<!-- 
    <div id="closeAll">
        <p>Fermer tous les détails</p>
    </div> -->

<!-- <div>
    <p>Je peux utiliser WordPress.</p>
</div> -->


<!-- Ancien projet, probablement inintéressant car fait en cours de formation -->

<!-- <a href="/projet-reservia">
    Cliquez moi pour voir mes autres projets
</a> -->

<script src="js/main.js"></script>